<div id="title">Image Attribution</div>
<table class="center" width="100%">
<tr><td class="center"><b>Image</b></td><td class="center"><b>Author</b></td><td class="center"><b>Location</b></td><td class="center"><b>License</b></td></tr>
<tr><td class="center"><img src="images/bridge.jpg" width="150"></td><td class="center">Petr Kratochvil</td><td class="center"><a href="index.php">http://wwww.pixelnations.net/beta/</a></td><td class="center"><a href="http://www.publicdomainpictures.net/view-image.php?image=8257">This image is public domain.</a></td></tr>
<tr><td class="center"><img src="images/navy.jpg" width="150"></td><td class="center">U.S. Navy photo by Mass Communication Specialist 2nd Class Katerine Noll</td><td class="center"><a href="index.php">http://wwww.pixelnations.net/beta/</a></td><td class="center"><a href="http://www.navy.mil/view_single.asp?id=121450">As a United States Navy image, it is available for public use.</a></td></tr>
<tr><td class="center"><img src="images/rocket.jpg" width="150"></td><td class="center">NASA</td><td class="center"><a href="index.php">http://wwww.pixelnations.net/beta/</a></td><td class="center"><a href="http://grin.hq.nasa.gov/ABSTRACTS/GPN-2000-000058.html">All NASA images are public domain.</a></td></tr>
<tr><td class="center"><img src="images/soldiers.jpg" width="150"></td><td class="center">U.S. Air Force photo by Staff Sgt. Dallas Edwards</td><td class="center"><a href="index.php">http://wwww.pixelnations.net/beta/</a></td><td class="center"><a href="http://www.ng.mil/resources/photo_gallery/index.html">This image is licensed for public use.</a></td></tr>
<tr><td class="center"><img src="images/airport.jpg" width="150"></td><td class="center">U.S. Air Force photo by Staff Sgt. Larry E. Reid Jr.</td><td class="center"><a href="index.php">http://wwww.pixelnations.net/beta/</a></td><td class="center"><a href="http://www.af.mil/photos/mediagallery.asp?galleryID=2&page=4">As a United States Air Force image, it is available for public use.</a></td></tr>
<tr><td class="center"><img src="images/space.jpg" width="150"></td><td class="center">NASA</td><td class="center"><a href="index.php">http://wwww.pixelnations.net/beta/</a></td><td class="center">All NASA images are public domain.</td></tr>
<tr><td class="center"><img src="images/ships.jpg" width="150"></td><td class="center">U.S. Navy photo by Aviation Warfare Systems Operator 3rd Class Shane Miller</td><td class="center"><a href="index.php">http://wwww.pixelnations.net/beta/</a></td><td class="center"><a href="http://www.navy.mil/view_single.asp?id=121551">As a United States Navy image, it is available for public use.</a></td></tr>
<tr><td class="center"><img src="images/harrier.jpg" width="150"></td><td class="center">U.S. Air Force photo by Master Sergeant Benjamin Bloker</td><td class="center"><a href="index.php">http://wwww.pixelnations.net/beta/</a></td><td class="center"><a href="http://www.af.mil/photos/slideshow.asp?id={BBFD077D-3F85-4D57-9C69-4D5D74242904}">As a United States Air Force image, it is available for public use.</a></td></tr>
<tr><td class="center"><img src="images/buysoldiers.jpg" width="150"></td><td class="center">U.S. Air Force photo by Tech. Sgt. Ashley Bell</td><td class="center"><a href="index.php?id=19">http://wwww.pixelnations.net/beta/index.php?id=19</a></td><td class="center"><a href="http://www.af.mil/photos/slideshow.asp?id={70F2183D-0F76-467E-BAA0-5BA8F1B89B74}">As a United States Air Force image, it is available for public use.</a></td></tr>
<tr><td class="center"><img src="images/buytanks.jpg" width="150"></td><td class="center">Spc. Ben Hutto, 3HBCT, 3rd ID</td><td class="center"><a href="index.php?id=20">http://wwww.pixelnations.net/beta/index.php?id=20</a></td><td class="center"><a href="http://www.army.mil/media/73979">As a United States Army image, it is available for public use.</a></td></tr>
<tr><td class="center"><img src="images/buyjets.jpg" width="150"></td><td class="center">U.S. Air Force photo by Master Sgt. Lance Cheung</td><td class="center"><a href="index.php?id=21">http://wwww.pixelnations.net/beta/index.php?id=21</a></td><td class="center"><a href="http://www.ng.mil/resources/photo_gallery/index.html">As a United States Air Force image, it is available for public use.</a></td></tr>

<tr><td class="center"><img src="images/buybattleship.jpg" width="150"></td><td class="center">U.S. Navy photo by Mass Communication Specialist 3rd Class Kenneth Abbate</td><td class="center"><a href="index.php?id=22">http://wwww.pixelnations.net/beta/index.php?id=22</a></td><td class="center"><a href="http://www.navy.mil/view_single.asp?id=115679">As a United States Navy image, it is available for public use.</a></td></tr>

<tr><td class="center"><img src="images/buymissiles.jpg" width="150"></td><td class="center">U.S. Department of Defense</td><td class="center"><a href="index.php?id=23">http://wwww.pixelnations.net/beta/index.php?id=23</a></td><td class="center"><a href="http://www.defense.gov/landing/privacy.aspx">Available for public use.</a></td></tr>
<tr><td class="center"><img src="images/declare.jpg" width="150"></td><td class="center">Sgt. Edward Balaban Arizona National Guard</td><td class="center"><a href="index.php?id=29">http://wwww.pixelnations.net/beta/index.php?id=29</a></td><td class="center"><a href="http://www.ng.mil/resources/photo_gallery/index.html">Available for public use.</a></td></tr>
<tr><td class="center"><img src="images/groundbattle.jpg" width="150"></td><td class="center">National Guard</td><td class="center"><a href="index.php?id=34">http://wwww.pixelnations.net/beta/index.php?id=34</a></td><td class="center"><a href="http://www.ng.mil/resources/photo_gallery/index.html">Available for public use.</a></td></tr>
<tr><td class="center"><img src="images/mywars.jpg" width="150"></td><td class="center">Charles Eckert</td><td class="center"><a href="index.php?id=30">http://wwww.pixelnations.net/beta/index.php?id=30</a></td><td class="center"><a href="http://www.ng.mil/resources/photo_gallery/index.html">Available for public use.</a></td></tr>
<tr><td class="center"><img src="images/seabattle.jpg" width="150"></td><td class="center">U.S. Navy photo by Mass Communication Specialist 2nd Class William Jamieson</td><td class="center"><a href="index.php?id=35">http://wwww.pixelnations.net/beta/index.php?id=35</a></td><td class="center"><a href="http://www.navy.mil/view_single.asp?id=123578">U.S. Navy Photo available for public use.</a></td></tr>
<tr><td class="center"><img src="images/airattack.jpg" width="150"></td><td class="center">U.S. Air Force photo by Master Sgt. Cohen A. Young</td><td class="center"><a href="index.php?id=36">http://wwww.pixelnations.net/beta/index.php?id=36</a></td><td class="center"><a href="http://www.af.mil/photos/mediagallery.asp?galleryID=11&page=6">U.S. Air Force Photo available for public use.</a></td></tr>
<tr><td class="center"><img src="images/nuke.jpg" width="150"></td><td class="center">Wittman80 (DeviantArt user)</td><td class="center"><a href="index.php?id=37">http://wwww.pixelnations.net/beta/index.php?id=37</a></td><td class="center"><a href="http://wittman80.deviantart.com/art/Mushroom-Cloud-145493522">Available for use.</a></td></tr>


<tr><td class="center"><img src="http://cdn1.iconfinder.com/data/icons/windows8_icons/26/sheep_on_bike.png"></td><td class="center"><a href="http://www.iconfinder.com/search/?q=iconset%3Awindows8_icons">Windows 8 Icon Set by Visual Pharm</a></td><td class="center"><a href="index.php">Various</a></td><td class="center"><a href="http://creativecommons.org/licenses/by/3.0/">Creative Commons 3.0</a></td></tr>

</table>

All other images used on this website are believed to be public domain images, available for use. If you believe your image is being used unfairly, please contact <a href="mailto:webmaster@pixelnations.net">webmaster@pixelnations.net</a> and it will be removed from the website as soon as possible.