<optgroup label="Real Flags">
<option  value="afghanistan.jpg">Afghanistan</option>
<option  value="africanunion.jpg">African Union</option>
<option  value="albania.jpg">Albania</option>
<option  value="algeria.jpg">Algeria</option>
<option  value="americansomoa.jpg">American Somoa</option>
<option  value="andorra.jpg">Andorra</option>
<option  value="angola.jpg">Angola</option>
<option  value="antiguaandbarbuda.jpg">Antigua & Barbuda</option>
<option  value="argentina.jpg">Argentina</option>
<option  value="armenia.jpg">Armenia</option>
<option  value="australia.jpg">Australia</option>
<option  value="austria.jpg">Austria</option>
<option  value="bahamas.jpg">Bahamas</option>
<option  value="bahrain.jpg">Bahrain</option>
<option  value="bangladesh.jpg">Bangladesh</option>
<option  value="barbados.jpg">Barbados</option>
<option  value="belgium.jpg">Belgium</option>
<option  value="belize.jpg">Belize</option>
<option  value="benin.jpg">Benin</option>
<option  value="bhutan.jpg">Bhutan</option>
<option  value="bolivia.jpg">Bolivia</option>
<option  value="brazil.jpg">Brazil</option>
<option  value="brunei.jpg">Brunei</option>
<option  value="bulgaria.jpg">Bulgaria</option>
<option  value="burundi.jpg">Burundi</option>
<option  value="cambodia.jpg">Cambodia</option>
<option  value="canada.jpg">Canada</option>
<option  value="capeverde.jpg">Cape Verde</option>
<option  value="chad.jpg">Chad</option>
<option  value="chile.jpg">Chile</option>
<option  value="china.jpg">China</option>
<option  value="colombia.jpg">Colombia</option>
<option  value="confederate.jpg">Confederate States of America</option>
<option  value="costarica.jpg">Costa Rica</option>
<option  value="croatia.jpg">Croatia</option>
<option  value="cuba.jpg">Cuba</option>
<option  value="cyprus.jpg">Cyprus</option>
<option  value="denmark.jpg">Denmark</option>
<option  value="djibouti.jpg">Djibouti</option>
<option  value="dominicanrepublic.jpg">Dominican Republic</option>
<option  value="ecuador.jpg">Ecuador</option>
<option  value="egypt.jpg">Egypt</option>
<option  value="estonia.jpg">Estonia</option>
<option  value="ethiopia.jpg">Ethiopia</option>
<option  value="europeanunion.jpg">European Union</option>
<option  value="fiji.jpg">Fiji</option>
<option  value="finland.jpg">Finland</option>
<option  value="france.jpg">France</option>
<option  value="georgia.jpg">Georgia</option>
<option  value="germany.jpg">Germany</option>
<option  value="greece.jpg">Greece</option>
<option  value="greenland.jpg">Greenland</option>
<option  value="grenada.jpg">Grenada</option>
<option  value="guatemala.jpg">Guatemala</option>
<option  value="guyana.jpg">Guyana</option>
<option  value="haiti.jpg">Haiti</option>
<option  value="honduras.jpg">Honduras</option>
<option  value="hungary.jpg">Hungary</option>
<option  value="iceland.jpg">Iceland</option>
<option  value="india.jpg">India</option>
<option  value="indonesia.jpg">Indonesia</option>
<option  value="iran.jpg">Iran</option>
<option  value="iraq.jpg">Iraq</option>
<option  value="ireland.jpg">Ireland</option>
<option  value="israel.jpg">Israel</option>
<option  value="italy.jpg">Italy</option>
<option  value="jamaica.jpg">Jamaica</option>
<option  value="japan.jpg">Japan</option>
<option  value="jordan.jpg">Jordan</option>
<option  value="kenya.jpg">Kenya</option>
<option  value="kuwait.jpg">Kuwait</option>
<option  value="laos.jpg">Laos</option>
<option  value="latvia.jpg">Latvia</option>
<option  value="lebanon.jpg">Lebanon</option>
<option  value="libya.jpg">Libya</option>
<option  value="lithuania.jpg">Lithuania</option>
<option  value="macedonia.jpg">Macedonia</option>
<option  value="malaysia.jpg">Malaysia</option>
<option  value="mali.jpg">Mali</option>
<option  value="malta.jpg">Malta</option>
<option  value="mexico.jpg">Mexico</option>
<option  value="moldova.jpg">Moldova</option>
<option  value="mongolia.jpg">Mongolia</option>
<option  value="netherlands.jpg">Netherlands</option>
<option  value="newzealand.jpg">New Zealand</option>
<option  value="nicaragua.jpg">Nicaragua</option>
<option  value="nigeria.jpg">Nigeria</option>
<option  value="norway.jpg">Norway</option>
<option  value="oman.jpg">Oman</option>
<option  value="pakistan.jpg">Pakistan</option>
<option  value="panama.jpg">Panama</option>
<option  value="papaunewguinea.jpg">Papua New Guinea</option>
<option  value="paraguay.jpg">Paraguay</option>
<option  value="peru.jpg">Peru</option>
<option  value="philippines.jpg">Philippines</option>
<option  value="poland.jpg">Poland</option>
<option  value="portugal.jpg">Portugal</option>
<option  value="qatar.jpg">Qatar</option>
<option  value="romania.jpg">Romania</option>
<option  value="russia.jpg">Russia</option>
<option  value="saudiarabia.jpg">Saudi Arabia</option>
<option  value="serbia.jpg">Serbia</option>
<option  value="sierraleone.jpg">Sierra Leone</option>
<option  value="slovakia.jpg">Slovakia</option>
<option  value="somalia.jpg">Somalia</option>
<option  value="southafrica.jpg">South Africa</option>
<option  value="southkorea.jpg">South Korea</option>
<option  value="sovietunion.jpg">Soviet Union</option>
<option  value="spain.jpg">Spain</option>
<option  value="srilanka.jpg">Sri Lanka</option>
<option  value="sudan.jpg">Sudan</option>
<option  value="sweden.jpg">Sweden</option>
<option  value="switzerland.jpg">Switzerland</option>
<option  value="syria.jpg">Syria</option>
<option  value="taiwan.jpg">Taiwan</option>
<option value="texas.jpg">Texas</option>
<option  value="thailand.jpg">Thailand</option>
<option  value="tibet.jpg">Tibet</option>
<option  value="trinidad.jpg">Trinidad & Tobago</option>
<option  value="tunisia.jpg">Tunisia</option>
<option  value="turkey.jpg">Turkey</option>
<option  value="uganda.jpg">Uganda</option>
<option  value="ukraine.jpg">Ukraine</option>
<option  value="unitedarabemirates.jpg">United Arab Emirates</option>
<option  value="unitedkingdom.jpg">United Kingdom</option>
<option  value="unitedstates.jpg">United States</option>
<option  value="uruguay.jpg">Uruguay</option>
<option  value="venezeula.jpg">Venezeula</option>
<option  value="vietnam.jpg">Vietnam</option>
<option  value="yemen.jpg">Yemen</option>
<option  value="zimbabwe.jpg">Zimbabwe</option>
</optgroup><optgroup label="Alliance Flags">
<option value="anto.jpg">ANTO</option>
<option value="exodite.gif">Exodite</option>
<option value="fan.jpg">FAN</option>
<option value="iss.jpg">Intl Socialist Syndicate</option>
<option value="poisonclan.jpg">Poison Clan</option>
<option value="theflock.jpg">The Flock</option>
<option value="thepolis.jpg">The Polis</option>
</optgroup><optgroup label="Custom Flags">
<option value="almaniania.jpg">Almaniania</option>
<option value="arryn.jpg">Arryn</option>
<option value="baratheon.jpg">Baratheon</option>
<option value="blooper.jpg">Blooper</option>
<option value="Crusader.jpg">Crusader</option>
<option value="clockwork.jpg">Hivemind</option>
<option value="lannister.jpg">Lannister</option>
<option value="martell.jpg">Martell</option>
<option value="NuclearFlag2.jpg">Nuclear</option>
<option value="salvarity.jpg">Salvarity</option>
<option value="stark.jpg">Stark</option>
<option value="targaryen.jpg">Targaryen</option>
<option value="tully.jpg">Tully</option>
<option value="tyrell.jpg">Tyrell</option>
</optgroup>
</select>